container:
  image: python:3-alpine

test2_task:
  container:
    image: python:2-alpine
  test_script: python2 test.py

test3_task:
  test_script: python3 test.py

build_package_test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python3 -m pip install --upgrade poetry
  build_package_test_script: poetry build

lint_task:
  container:
    image: alpine/flake8:latest
  script: flake8 *.py
