container:
  image: python:3-alpine

python2_tests_task:
  container:
    image: python:2-alpine
  test_script: python2 test.py

python3_tests_task:
  test_script: python3 test.py

build_package_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat pyproject.toml
    populate_script: apk add gcc musl-dev libffi-dev openssl-dev && python3 -m pip install --upgrade poetry
  build_package_test_script: poetry build

flake8_task:
  container:
    image: alpine/flake8:latest
  script: flake8 --ignore=E128,E261 --max-line-length=120 .
