container:
  image: python:3-alpine

python_2_tests_task:
  container:
    image: python:2-alpine
  test_script: python2 test.py

python_3_tests_task:
  test_script: python3 test.py

build_package_task:
  pip_cache:
    folder: ~/.cache/pip
    # there appears to be a cirrus bug with uploading the pip cache, so use the date to force a rebuild each time
    fingerprint_script: echo $PYTHON_VERSION && date -u
    populate_script: python3 -m pip install --upgrade poetry
  build_package_test_script: poetry build

flake8_task:
  container:
    image: alpine/flake8:latest
  script: flake8 --ignore=E128,E261 --max-line-length=120 .
